/** @const {ShadowJS} */ var Page;
/** @const {ShadowJS} */ var Reflect;
/** @const {ShadowJS} */ var module;
/** @const {ShadowJS} */ var wx;
ShadowJS.prototype.callFunction;
ShadowJS.prototype.cloud;
ShadowJS.prototype.has;
ShadowJS.prototype.isFinite;
ShadowJS.prototype.navigateTo;
ShadowJS.prototype.setClipboardData;
ShadowJS.prototype.showToast;